"""Re-export from disaster submodule for backward compatibility."""
from .disaster.queries import (
    CREATE_CONSTRAINTS, CREATE_INDEXES,
    MERGE_EVENT, MERGE_ATTRIBUTE, MERGE_ATTRIBUTE_DEDUP,
    MERGE_ATTRIBUTE_DEDUP_SIMPLE, MERGE_ATTRIBUTE_DEDUP_CREATE,
    MERGE_LOCATION, MERGE_SOURCE_DOC,
    MERGE_HAS_ATTRIBUTE, MERGE_OCCURRED_AT, MERGE_REPORTED_BY, MERGE_EVIDENCED_BY,
    QUERY_EVENT_WITH_CONTEXT, QUERY_EVENTS_BY_TYPE,
    QUERY_RECENT_EVENTS, QUERY_ATTRIBUTES_BY_KEY, QUERY_EVENT_BY_NAME_FUZZY,
    event_params, attribute_params, location_params, source_doc_params,
)
